export const karnatakaData = {
  Bagalkot: ["Bagalkot", "Badami", "Jamkhandi", "Mudhol"],
  Ballari: ["Ballari", "Hospet", "Kudligi", "Sandur"],
  Belagavi: ["Belagavi", "Athani", "Chikkodi", "Gokak", "Khanapur"],
  BengaluruUrban: ["Bengaluru", "Yelahanka", "KR Puram", "Whitefield"],
  BengaluruRural: ["Devanahalli", "Doddaballapur", "Hosakote", "Nelamangala"],
  Bidar: ["Bidar", "Basavakalyan", "Bhalki", "Aurad"],
  Vijayapura: ["Vijayapura", "Indi", "Sindagi", "Muddebihal"],
  Chamarajanagar: ["Chamarajanagar", "Kollegal", "Yelandur", "Hanur"],
  Chikkaballapur: ["Chikkaballapur", "Sidlaghatta", "Bagepalli", "Gauribidanur"],
  Chikkamagaluru: ["Chikkamagaluru", "Tarikere", "Kadur", "Mudigere"],
  Chitradurga: ["Chitradurga", "Hosadurga", "Hiriyur", "Molakalmuru"],
  DakshinaKannada: ["Mangaluru", "Bantwal", "Puttur", "Sullia"],
  Davanagere: ["Davanagere", "Harihar", "Honnali", "Channagiri"],
  Dharwad: ["Dharwad", "Hubballi", "Kalghatgi", "Navalgund"],
  Gadag: ["Gadag", "Mundaragi", "Nargund", "Shirahatti"],
  Kalaburagi: ["Kalaburagi", "Afzalpur", "Chincholi", "Sedam"],
  Hassan: ["Hassan", "Arsikere", "Belur", "Channarayapatna"],
  Haveri: ["Haveri", "Ranebennur", "Byadgi", "Hirekerur"],
  Kodagu: ["Madikeri", "Somwarpet", "Virajpet"],
  Kolar: ["Kolar", "Malur", "Mulbagal", "Bangarpet"],
  Koppal: ["Koppal", "Gangavati", "Kushtagi", "Yelburga"],
  Mandya: ["Mandya", "Maddur", "Srirangapatna", "Nagamangala"],
  Mysuru: ["Mysuru", "Nanjangud", "Hunsur", "T Narasipura"],
  Raichur: ["Raichur", "Sindhanur", "Manvi", "Lingasugur"],
  Ramanagara: ["Ramanagara", "Kanakapura", "Channapatna", "Magadi"],
  Shivamogga: ["Shivamogga", "Bhadravati", "Sagar", "Tirthahalli"],
  Tumakuru: ["Tumakuru", "Sira", "Tiptur", "Gubbi"],
  Udupi: ["Udupi", "Kundapura", "Karkala"],
  UttaraKannada: ["Karwar", "Sirsi", "Ankola", "Bhatkal"],
  Vijayanagara: ["Hospet", "Kudligi", "Hagaribommanahalli"],
  Yadgir: ["Yadgir", "Shorapur", "Gurumitkal"]
};