import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import "./styles/HomePage.css";
import {
  FaUser,
  FaBuilding,
  FaLandmark,
  FaFileInvoiceDollar,
  FaHome,
  FaGavel,
  FaArrowRight,
  FaCheckCircle,
  FaShieldAlt,
  FaClock,
  FaAward,
  FaCertificate,
  FaChevronDown,
  FaChevronUp,
  FaQuestionCircle
} from "react-icons/fa";
import MasterVerificationSearchBar from "../components/MasterVerificationSearchBar";

const buttonPillarStyle = (bg, border) => ({
  background: bg,
  color: "#ffffff",
  padding: "12px 20px",
  borderRadius: "12px",
  fontWeight: "800",
  textDecoration: "none",
  fontSize: "0.95rem",
  border: `1px solid ${border}`,
  boxShadow: "0 4px 14px rgba(0,0,0,0.25)",
  whiteSpace: "nowrap",
  display: "inline-flex",
  alignItems: "center",
  gap: "10px",
  transition: "all 0.2s ease-in-out"
});

export default function HomePage() {
  const [openFaq, setOpenFaq] = useState(null);

  const toggleFaq = (index) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  const primaryOffices = [
    {
      id: "municipality",
      num: "1",
      title: "Municipality Office Portal",
      icon: <FaBuilding />,
      color: "#0284c7",
      bgColor: "#f0f9ff",
      borderColor: "#7dd3fc",
      link: "/login?role=municipality",
      sla: "24-48 Hours",
      services: [
        "Birth & Death Certificate Verification",
        "Marriage Registration & Certificate",
        "Property Tax Ledger & Dues Clearance",
        "Water & Sanitation Connection NOC",
        "Trade & Commercial Operations License",
        "Building Plan & Occupancy Approval"
      ]
    },
    {
      id: "tehsildar",
      num: "2",
      title: "Tehsildar Executive Office",
      icon: <FaLandmark />,
      color: "#15803d",
      bgColor: "#f0fdf4",
      borderColor: "#86efac",
      link: "/login?role=tehsildar",
      sla: "24-48 Hours",
      services: [
        "Domicile & Residence Certificate",
        "Income Certificate & Asset Evaluation",
        "Caste & Ancestral Identity Verification",
        "Solvency Certificate for Guarantees",
        "Agriculturist Certificate & Land NOC",
        "Legal Heirship & Family Succession"
      ]
    },
    {
      id: "revenue",
      num: "3",
      title: "Revenue & Land Assessment",
      icon: <FaFileInvoiceDollar />,
      color: "#b45309",
      bgColor: "#fffbeb",
      borderColor: "#fde68a",
      link: "/login?role=revenue",
      sla: "24-48 Hours",
      services: [
        "Land Revenue Tax Ledger & Receipts",
        "Property Mutation (Ferfar) Audit",
        "Encumbrance Certificate (Non-Encumbrance)",
        "Revenue Court Dispute Clearance",
        "Non-Agricultural (NA) Land Use NOC",
        "Crop Damage Valuation & Tax Relief"
      ]
    },
    {
      id: "talati",
      num: "4",
      title: "Talati / Gram Panchayat Office",
      icon: <FaHome />,
      color: "#7c3aed",
      bgColor: "#f3e8ff",
      borderColor: "#c084fc",
      link: "/login?role=talati",
      sla: "24 Hours",
      services: [
        "7/12 & 8-A Rights Extracts Verification",
        "Haqq Mutation (Ferfar) Register Audit",
        "Boundary Dispute & Spot Field Audit",
        "Crop Yield & Pani Patrak Register",
        "Village Residence Confirmation",
        "Village Ancestral Caste Verification"
      ]
    }
  ];

  const faqs = [
    {
      q: "How does single-form multi-office routing work?",
      a: "When a citizen files an application, E-Gov-Connect creates a single digital record that automatically routes across local Municipality, Tehsildar, Revenue, and Talati offices. Citizens track progress without filling redundant forms or visiting separate counters."
    },
    {
      q: "What happens if an officer delays an application beyond 48 hours?",
      a: "Our automated 48-Hour SLA Resolver Engine continuously monitors queue times. Applications stalled beyond 48 hours are automatically escalated to the Resolver Portal with automated warning email dispatch to officials."
    },
    {
      q: "How does the Discrepancy Feedback Loop prevent arbitrary rejections?",
      a: "Officers flag specific document missing items instead of rejecting files outright. Citizens re-upload missing documents directly through the Discrepancy Loop without fee repayments or fresh applications."
    },
    {
      q: "Are issued certificates digitally signed and tamper-proof?",
      a: "Yes! Every certificate generated by the system contains a cryptographic PKI digital signature from the verifying officer along with an embedded QR code for instant public verification."
    }
  ];

  return (
    <div className="homepage" style={{ fontFamily: "'Inter', sans-serif", background: "#f8fafc", color: "#0f172a", minHeight: "100vh" }}>
      
      {/* 🌟 HERO BANNER */}
      <section
        style={{
          background: "linear-gradient(135deg, #064e3b 0%, #047857 45%, #0f172a 100%)",
          color: '#ffffff',
          textAlign: 'center',
          padding: '4.5rem 1.5rem 5rem 1.5rem',
          position: 'relative'
        }}
      >
        <div style={{ maxWidth: "1200px", margin: "0 auto" }}>
          
          <div style={{ display: "inline-flex", alignItems: "center", gap: "8px", background: "rgba(255,255,255,0.15)", backdropFilter: "blur(8px)", border: "1px solid rgba(255,255,255,0.3)", padding: "6px 18px", borderRadius: "30px", fontSize: "0.85rem", fontWeight: "800", color: "#a7f3d0", marginBottom: "20px" }}>
            <FaAward /> SIH 2026 OFFICIAL SUBMISSION • FEDERATED 4-OFFICE E-GOVERNANCE ECOSYSTEM
          </div>

          <h1 style={{ color: "#ffffff", fontSize: "3.2rem", fontWeight: "900", margin: "0 0 16px 0", letterSpacing: "-1px", lineHeight: "1.2" }}>
            E-Gov-Connect Governance Platform
          </h1>

          <p style={{ color: "#d1fae5", fontSize: "1.2rem", maxWidth: "900px", margin: "0 auto 36px auto", lineHeight: "1.6", fontWeight: "400" }}>
            Unified citizen portal with dynamic forms, automated multi-office sequential routing across <strong>Municipality</strong>, <strong>Tehsildar</strong>, <strong>Revenue</strong>, and <strong>Talati</strong>, live dues clearance, 48-hour auto-escalation to Resolver, and digitally signed certificate generation.
          </p>

          {/* 6 Quick-Access Role Pill Buttons */}
          <div style={{ display: "flex", flexWrap: "wrap", gap: "12px", justifyContent: "center", alignItems: "center" }}>
            <Link to="/login?role=citizen" style={buttonPillarStyle("linear-gradient(135deg, #15803d, #166534)", "#86efac")}>
              <FaUser /> 🟢 Citizen Services
            </Link>
            <Link to="/login?role=municipality" style={buttonPillarStyle("linear-gradient(135deg, #0c4a6e, #0284c7)", "#7dd3fc")}>
              <FaBuilding /> 🏢 Municipality Office
            </Link>
            <Link to="/login?role=tehsildar" style={buttonPillarStyle("linear-gradient(135deg, #14532d, #166534)", "#86efac")}>
              <FaLandmark /> 📜 Tehsildar Office
            </Link>
            <Link to="/login?role=revenue" style={buttonPillarStyle("linear-gradient(135deg, #78350f, #b45309)", "#fde68a")}>
              <FaFileInvoiceDollar /> 🌾 Revenue Office
            </Link>
            <Link to="/login?role=talati" style={buttonPillarStyle("linear-gradient(135deg, #581c87, #7c3aed)", "#ddd6fe")}>
              <FaHome /> 🏡 Talati Office
            </Link>
            <Link to="/login?role=resolver" style={buttonPillarStyle("linear-gradient(135deg, #991b1b, #dc2626)", "#fca5a5")}>
              <FaGavel /> ⚖️ Resolver Portal
            </Link>
          </div>

        </div>
      </section>

      {/* 🏢 4 SEPARATE GOVERNMENT OFFICES + RESOLVER PORTAL */}
      <section style={{ maxWidth: "1200px", margin: "40px auto 60px auto", padding: "0 1.5rem" }}>
        
        <div style={{ textAlign: "center", marginBottom: "40px" }}>
          <span style={{ background: "#e0f2fe", color: "#0284c7", padding: "5px 16px", borderRadius: "20px", fontSize: "0.8rem", fontWeight: "900", textTransform: "uppercase", letterSpacing: "0.5px" }}>
            FEDERATED DIGITAL WORKSPACES
          </span>
          <h2 style={{ fontSize: "2.4rem", fontWeight: "900", color: "#0f172a", margin: "10px 0 6px 0", letterSpacing: "-0.5px" }}>
            4 Separate Government Offices + Resolver Portal
          </h2>
          <p style={{ color: "#64748b", fontSize: "1.05rem", maxWidth: "750px", margin: "0 auto" }}>
            Click on any office below to enter its standalone digital workspace, review application queues, execute 1-minute verifications, and sign digital certificates.
          </p>
        </div>

        {/* 2x2 Grid for Primary Offices */}
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(450px, 1fr))", gap: "28px", marginBottom: "32px" }}>
          {primaryOffices.map((off) => (
            <div
              key={off.id}
              style={{
                background: "#ffffff",
                borderRadius: "20px",
                border: `2px solid ${off.borderColor}`,
                boxShadow: "0 10px 30px -5px rgba(0,0,0,0.06)",
                overflow: "hidden",
                display: "flex",
                flexDirection: "column",
                justifyContent: "space-between",
                transition: "transform 0.2s ease, boxShadow 0.2s ease"
              }}
            >
              <div>
                {/* Header Strip */}
                <div style={{ background: off.bgColor, padding: "20px 24px", borderBottom: `1px solid ${off.borderColor}`, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: "14px" }}>
                    <div style={{ background: off.color, color: "#ffffff", width: "48px", height: "48px", borderRadius: "14px", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "1.4rem", boxShadow: "0 4px 10px rgba(0,0,0,0.15)" }}>
                      {off.icon}
                    </div>
                    <div>
                      <span style={{ fontSize: "0.75rem", fontWeight: "900", color: off.color, textTransform: "uppercase", letterSpacing: "1px" }}>
                        OFFICE WORKSPACE #{off.num}
                      </span>
                      <h3 style={{ margin: "2px 0 0 0", color: "#0f172a", fontSize: "1.3rem", fontWeight: "900" }}>
                        {off.title}
                      </h3>
                    </div>
                  </div>

                  <span style={{ background: "#ffffff", color: off.color, border: `1px solid ${off.borderColor}`, padding: "6px 14px", borderRadius: "20px", fontSize: "0.8rem", fontWeight: "900", boxShadow: "0 2px 6px rgba(0,0,0,0.04)" }}>
                    ⏱️ SLA: {off.sla}
                  </span>
                </div>

                {/* Body Content */}
                <div style={{ padding: "24px" }}>
                  <p style={{ margin: "0 0 14px 0", fontSize: "0.85rem", fontWeight: "800", color: "#475569", textTransform: "uppercase", letterSpacing: "0.5px" }}>
                    Statutory Services &amp; Verification Scope:
                  </p>

                  <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px 16px" }}>
                    {off.services.map((s, idx) => (
                      <div key={idx} style={{ display: "flex", alignItems: "flex-start", gap: "8px", fontSize: "0.86rem", color: "#334155", lineHeight: "1.4" }}>
                        <FaCheckCircle style={{ color: off.color, marginTop: "3px", flexShrink: 0 }} />
                        <span>{s}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              {/* Action Button Footer */}
              <div style={{ padding: "0 24px 24px 24px" }}>
                <Link
                  to={off.link}
                  style={{
                    textDecoration: "none",
                    background: off.color,
                    color: "white",
                    padding: "14px 20px",
                    borderRadius: "12px",
                    fontWeight: "800",
                    fontSize: "0.95rem",
                    textAlign: "center",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    gap: "10px",
                    boxShadow: "0 4px 14px rgba(0,0,0,0.15)",
                    transition: "opacity 0.2s ease"
                  }}
                >
                  Enter {off.title} Workspace <FaArrowRight />
                </Link>
              </div>
            </div>
          ))}
        </div>

        {/* 🌟 PROMINENT FEATURED RESOLVER AUTHORITY PORTAL CARD */}
        <div
          style={{
            background: "linear-gradient(135deg, #7f1d1d 0%, #991b1b 50%, #450a0a 100%)",
            color: "#ffffff",
            borderRadius: "24px",
            padding: "32px",
            border: "2px solid #fca5a5",
            boxShadow: "0 15px 35px -5px rgba(153,27,27,0.3)",
            display: "flex",
            flexDirection: "column",
            justify: "space-between",
            gap: "24px"
          }}
        >
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: "16px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "16px" }}>
              <div style={{ background: "#fee2e2", color: "#991b1b", width: "56px", height: "56px", borderRadius: "16px", display: "flex", alignItems: "center", justifyContent: "center", fontSize: "1.8rem", boxShadow: "0 4px 12px rgba(0,0,0,0.2)" }}>
                <FaGavel />
              </div>
              <div>
                <span style={{ background: "#fca5a5", color: "#7f1d1d", padding: "4px 12px", borderRadius: "12px", fontSize: "0.78rem", fontWeight: "900", textTransform: "uppercase", letterSpacing: "1px" }}>
                  DISCIPLINARY &amp; ESCALATION AUTHORITY
                </span>
                <h3 style={{ margin: "4px 0 0 0", color: "#ffffff", fontSize: "1.8rem", fontWeight: "900" }}>
                  5. Resolver Authority Portal
                </h3>
              </div>
            </div>

            <span style={{ background: "#fee2e2", color: "#991b1b", padding: "8px 18px", borderRadius: "20px", fontSize: "0.85rem", fontWeight: "900", boxShadow: "0 2px 8px rgba(0,0,0,0.2)" }}>
              ⚖️ 48-Hour SLA Guarantee Enforcement
            </span>
          </div>

          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))", gap: "12px 20px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "10px", fontSize: "0.92rem", color: "#fecdd3" }}>
              <FaCheckCircle style={{ color: "#fca5a5" }} />
              <span>48-Hour SLA Unresponsiveness Auto-Escalation</span>
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: "10px", fontSize: "0.92rem", color: "#fecdd3" }}>
              <FaCheckCircle style={{ color: "#fca5a5" }} />
              <span>Officer Location Jurisdiction Profile Registry</span>
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: "10px", fontSize: "0.92rem", color: "#fecdd3" }}>
              <FaCheckCircle style={{ color: "#fca5a5" }} />
              <span>Disciplinary Warning Email Dispatch Gateway</span>
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: "10px", fontSize: "0.92rem", color: "#fecdd3" }}>
              <FaCheckCircle style={{ color: "#fca5a5" }} />
              <span>Cross-Office Pending File Re-assignment</span>
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: "10px", fontSize: "0.92rem", color: "#fecdd3" }}>
              <FaCheckCircle style={{ color: "#fca5a5" }} />
              <span>Multi-State Jurisdiction Override Controller</span>
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: "10px", fontSize: "0.92rem", color: "#fecdd3" }}>
              <FaCheckCircle style={{ color: "#fca5a5" }} />
              <span>Real-time Escalated Queue Audit Log</span>
            </div>
          </div>

          <div style={{ display: "flex", justifyContent: "flex-end" }}>
            <Link
              to="/login?role=resolver"
              style={{
                textDecoration: "none",
                background: "#ffffff",
                color: "#991b1b",
                padding: "14px 28px",
                borderRadius: "12px",
                fontWeight: "900",
                fontSize: "1rem",
                display: "inline-flex",
                alignItems: "center",
                gap: "10px",
                boxShadow: "0 4px 14px rgba(0,0,0,0.3)"
              }}
            >
              Enter Resolver Authority Portal Workspace <FaArrowRight />
            </Link>
          </div>
        </div>

      </section>

      {/* 🚀 KEY TECHNOLOGICAL HIGHLIGHTS */}
      <section style={{ maxWidth: "1200px", margin: "0 auto 60px auto", padding: "0 1.5rem" }}>
        <div style={{ textAlign: "center", marginBottom: "36px" }}>
          <span style={{ background: "#f3e8ff", color: "#7c3aed", padding: "5px 16px", borderRadius: "20px", fontSize: "0.8rem", fontWeight: "900", textTransform: "uppercase" }}>
            SYSTEM CAPABILITIES
          </span>
          <h2 style={{ fontSize: "2.2rem", fontWeight: "900", color: "#0f172a", margin: "10px 0 6px 0" }}>
            Key Platform Highlights &amp; SIH Innovations
          </h2>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: "20px" }}>
          
          <div style={{ background: "#ffffff", padding: "24px", borderRadius: "16px", border: "1px solid #e2e8f0", boxShadow: "0 4px 14px rgba(0,0,0,0.03)" }}>
            <FaClock style={{ fontSize: "2rem", color: "#059669", marginBottom: "12px" }} />
            <h4 style={{ margin: "0 0 6px 0", fontSize: "1.1rem", fontWeight: "800", color: "#0f172a" }}>1-Minute Verification</h4>
            <p style={{ margin: 0, fontSize: "0.85rem", color: "#64748b", lineHeight: "1.5" }}>
              Embedded Master Verification Bar enables officers to cross-verify 1,000 member records (Khata, Survey #, Property ID) in under 60 seconds.
            </p>
          </div>

          <div style={{ background: "#ffffff", padding: "24px", borderRadius: "16px", border: "1px solid #e2e8f0", boxShadow: "0 4px 14px rgba(0,0,0,0.03)" }}>
            <FaShieldAlt style={{ fontSize: "2rem", color: "#0284c7", marginBottom: "12px" }} />
            <h4 style={{ margin: "0 0 6px 0", fontSize: "1.1rem", fontWeight: "800", color: "#0f172a" }}>Discrepancy Feedback Loop</h4>
            <p style={{ margin: 0, fontSize: "0.85rem", color: "#64748b", lineHeight: "1.5" }}>
              Eliminates arbitrary rejections. Allows structured document re-submission without fee repayment or fresh application filing.
            </p>
          </div>

          <div style={{ background: "#ffffff", padding: "24px", borderRadius: "16px", border: "1px solid #e2e8f0", boxShadow: "0 4px 14px rgba(0,0,0,0.03)" }}>
            <FaGavel style={{ fontSize: "2rem", color: "#dc2626", marginBottom: "12px" }} />
            <h4 style={{ margin: "0 0 6px 0", fontSize: "1.1rem", fontWeight: "800", color: "#0f172a" }}>48h SLA Auto-Escalation</h4>
            <p style={{ margin: 0, fontSize: "0.85rem", color: "#64748b", lineHeight: "1.5" }}>
              Automated SLA monitor flags stagnant applications after 48 hours, dispatching warning emails to officials and re-assigning work to Resolver.
            </p>
          </div>

          <div style={{ background: "#ffffff", padding: "24px", borderRadius: "16px", border: "1px solid #e2e8f0", boxShadow: "0 4px 14px rgba(0,0,0,0.03)" }}>
            <FaCertificate style={{ fontSize: "2rem", color: "#7c3aed", marginBottom: "12px" }} />
            <h4 style={{ margin: "0 0 6px 0", fontSize: "1.1rem", fontWeight: "800", color: "#0f172a" }}>Digital Signatures &amp; QR</h4>
            <p style={{ margin: 0, fontSize: "0.85rem", color: "#64748b", lineHeight: "1.5" }}>
              Every issued certificate features cryptographic digital signatures and embedded QR verification code for 100% tamper-proof validity.
            </p>
          </div>

        </div>
      </section>

      {/* ❓ FREQUENTLY ASKED QUESTIONS (FAQ) */}
      <section style={{ maxWidth: "1000px", margin: "0 auto 80px auto", padding: "0 1.5rem" }}>
        <div style={{ textAlign: "center", marginBottom: "36px" }}>
          <span style={{ background: "#fef3c7", color: "#b45309", padding: "5px 16px", borderRadius: "20px", fontSize: "0.8rem", fontWeight: "900", textTransform: "uppercase" }}>
            FREQUENTLY ASKED QUESTIONS
          </span>
          <h2 style={{ fontSize: "2.2rem", fontWeight: "900", color: "#0f172a", margin: "10px 0 6px 0" }}>
            Project Implementation Details
          </h2>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
          {faqs.map((faq, idx) => (
            <div
              key={idx}
              style={{
                background: "#ffffff",
                borderRadius: "14px",
                border: "1px solid #cbd5e1",
                overflow: "hidden"
              }}
            >
              <button
                onClick={() => toggleFaq(idx)}
                style={{
                  width: "100%",
                  padding: "18px 22px",
                  background: openFaq === idx ? "#f1f5f9" : "#ffffff",
                  border: "none",
                  textAlign: "left",
                  fontSize: "1rem",
                  fontWeight: "800",
                  color: "#0f172a",
                  cursor: "pointer",
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center"
                }}
              >
                <span style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                  <FaQuestionCircle style={{ color: "#0284c7" }} /> {faq.q}
                </span>
                {openFaq === idx ? <FaChevronUp style={{ color: "#64748b" }} /> : <FaChevronDown style={{ color: "#64748b" }} />}
              </button>

              {openFaq === idx && (
                <div style={{ padding: "18px 22px", fontSize: "0.92rem", color: "#475569", lineHeight: "1.6", borderTop: "1px solid #e2e8f0", background: "#f8fafc" }}>
                  {faq.a}
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* 🏛️ FOOTER */}
      <footer style={{ background: "#0f172a", color: "#94a3b8", padding: "40px 1.5rem 24px 1.5rem", borderTop: "4px solid #059669" }}>
        <div style={{ maxWidth: "1200px", margin: "0 auto", display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "30px", marginBottom: "30px" }}>
          
          <div>
            <h3 style={{ color: "#ffffff", fontSize: "1.2rem", fontWeight: "900", margin: "0 0 10px 0" }}>
              🏛️ E-Gov-Connect
            </h3>
            <p style={{ fontSize: "0.83rem", lineHeight: "1.6", margin: 0 }}>
              Federated 4-Office E-Governance Ecosystem. Automated multi-office sequential routing across Municipality, Tehsildar, Revenue, and Talati with 48-Hour SLA Resolver Authority.
            </p>
          </div>

          <div>
            <h4 style={{ color: "#ffffff", fontSize: "0.95rem", fontWeight: "800", margin: "0 0 12px 0" }}>
              Standalone Office Portals
            </h4>
            <ul style={{ listStyle: "none", padding: 0, margin: 0, fontSize: "0.85rem", display: "flex", flexDirection: "column", gap: "8px" }}>
              <li><Link to="/login?role=citizen" style={{ color: "#cbd5e1", textDecoration: "none" }}>🟢 Citizen Portal</Link></li>
              <li><Link to="/login?role=municipality" style={{ color: "#cbd5e1", textDecoration: "none" }}>🏢 Municipality Portal</Link></li>
              <li><Link to="/login?role=tehsildar" style={{ color: "#cbd5e1", textDecoration: "none" }}>📜 Tehsildar Portal</Link></li>
              <li><Link to="/login?role=revenue" style={{ color: "#cbd5e1", textDecoration: "none" }}>🌾 Revenue Portal</Link></li>
              <li><Link to="/login?role=talati" style={{ color: "#cbd5e1", textDecoration: "none" }}>🏡 Talati Portal</Link></li>
              <li><Link to="/login?role=resolver" style={{ color: "#cbd5e1", textDecoration: "none" }}>⚖️ Resolver Portal</Link></li>
            </ul>
          </div>

          <div>
            <h4 style={{ color: "#ffffff", fontSize: "0.95rem", fontWeight: "800", margin: "0 0 12px 0" }}>
              Governance Standards
            </h4>
            <ul style={{ listStyle: "none", padding: 0, margin: 0, fontSize: "0.83rem", lineHeight: "1.8" }}>
              <li>• SIH 2026 Official Submission</li>
              <li>• Cryptographic PKI Digital Signatures</li>
              <li>• 1-Minute Master DB Verification</li>
              <li>• Automated 48-Hour SLA Discrepancy Engine</li>
            </ul>
          </div>

        </div>

        <div style={{ maxWidth: "1200px", margin: "0 auto", borderTop: "1px solid #334155", paddingTop: "20px", textAlign: "center", fontSize: "0.8rem", color: "#64748b" }}>
          © 2026 E-Gov-Connect Federated Governance Platform. Smart India Hackathon (SIH 2026) Prototype. All rights reserved.
        </div>
      </footer>

    </div>
  );
}